"""Add column to club database

Revision ID: 9ed5b22b20c0
Revises: 07b1d8bfa96e
Create Date: 2023-09-18 13:03:24.858191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed5b22b20c0'
down_revision: Union[str, None] = '07b1d8bfa96e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('number_of_members', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'number_of_members')
    # ### end Alembic commands ###
